### ISSUE TITLE
Swift Build not Working on Ubuntu 16.04

### ISSUE THREAD

**Issue by moosichu** [tid-kijyun/Kanna#134]
### Description:

Swift Version: 
```bash
Swift version 3.0.2 (swift-3.0.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

Get a bunch of errors, including:
```bash
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
```

Which doesn't seem right, as `xmlversion.h` definitely exists in `/usr/include/libxml2`.

Package.swift:

```swift
import PackageDescription

let package = Package(
    name: "cl_scraper",

    dependencies: [
        .Package(url: "https://github.com/tid-kijyun/Kanna.git", majorVersion: 2)
    ]
)
```

### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [x] v2.1.1
- [ ] other: ()

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [x] other: (On Linux)

**Comment by tid-kijyun** [comment]
Did you run this command?

```
$ sudo apt-get install libxml2-dev
```

**Comment by moosichu** [comment]
Yes

**Comment by moosichu** [comment]
```bash
ls /usr/include/libxml2/libxml/
c14n.h        list.h              tree.h         xmlregexp.h
catalog.h     nanoftp.h           uri.h          xmlsave.h
chvalid.h     nanohttp.h          valid.h        xmlschemas.h
debugXML.h    parser.h            xinclude.h     xmlschemastypes.h
dict.h        parserInternals.h   xlink.h        xmlstring.h
DOCBparser.h  pattern.h           xmlautomata.h  xmlunicode.h
encoding.h    relaxng.h           xmlerror.h     xmlversion.h
entities.h    SAX2.h              xmlexports.h   xmlwriter.h
globals.h     SAX.h               xmlIO.h        xpath.h
hash.h        schemasInternals.h  xmlmemory.h    xpathInternals.h
HTMLparser.h  schematron.h        xmlmodule.h    xpointer.h
HTMLtree.h    threads.h           xmlreader.h
```

**Comment by moosichu** [comment]
In tree.h, if I change the line causing the error from:
```c
#include <libxml/xmlversion.h>
```
to:
```c
#include <xmlversion.h>
```

Then the following error dissapears:

```bash
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
```

However, there are still many other errors. But I'm assuming the root of the issue is that the includes are looking in the wrong place for other headers in the library!

**Comment by tid-kijyun** [comment]
I'll download the same version and try it. Please give me some time.

**Comment by moosichu** [comment]
Thank you! Just been trying to list as much info I can obtain as possible in order to help.

**Comment by moosichu** [comment]
Some more information, I tried compiling the following extremely simple C program:

```c

#import <libxml2/libxml/tree.h>

void main() {
    printf("Hello, world!");
}

```

And got the following output:

```bash
$ clang test.c
In file included from test.c:1:
/usr/include/libxml2/libxml/tree.h:17:10: fatal error: 'libxml/xmlversion.h'
      file not found
#include <libxml/xmlversion.h>
         ^
1 error generated.
```

**Comment by tid-kijyun** [comment]
Please tell me the `swift build` log.

**Comment by moosichu** [comment]
This?

```bash
$ swift build
note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

Compile Swift Module 'Kanna' (5 sources)
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2.h"
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:9: note: in file included from /home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:
#import <libxml2/libxml/tree.h>
        ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/Kanna-2.1.1/Sources/Kanna/Kanna.swift:28:8: error: could not build Objective-C module 'SwiftClibxml2'
import SwiftClibxml2
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2.h"
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:9: note: in file included from /home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:
#import <libxml2/libxml/tree.h>
        ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/Kanna-2.1.1/Sources/Kanna/Kanna.swift:28:8: error: could not build Objective-C module 'SwiftClibxml2'
import SwiftClibxml2
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2.h"
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:9: note: in file included from /home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:
#import <libxml2/libxml/tree.h>
        ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/Kanna-2.1.1/Sources/Kanna/Kanna.swift:28:8: error: could not build Objective-C module 'SwiftClibxml2'
import SwiftClibxml2
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2.h"
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:9: note: in file included from /home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:
#import <libxml2/libxml/tree.h>
        ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/Kanna-2.1.1/Sources/Kanna/Kanna.swift:28:8: error: could not build Objective-C module 'SwiftClibxml2'
import SwiftClibxml2
       ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "libxml2.h"
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:9: note: in file included from /home/tom/Documents/swift-workshop/cl_scraper/Packages/SwiftClibxml2-1.0.2/libxml2.h:1:
#import <libxml2/libxml/tree.h>
        ^
/usr/include/libxml2/libxml/tree.h:17:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/home/tom/Documents/swift-workshop/cl_scraper/Packages/Kanna-2.1.1/Sources/Kanna/Kanna.swift:28:8: error: could not build Objective-C module 'SwiftClibxml2'
import SwiftClibxml2
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/tom/Programs/swift-3.0.2-RELEASE-ubuntu16.04/usr/bin/swift-build-tool -f /home/tom/Documents/swift-workshop/cl_scraper/.build/debug.yaml
```

**Comment by tid-kijyun** [comment]
Thank you.
Please look at line 2 to line 5.

```
note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev
```

It seems that the following command is not executed correctly. Please try again.

```
$ sudo apt-get install libxml2-dev
```

**Comment by moosichu** [comment]
^^ Already tried about 10 times now :(
```bash
$ sudo apt-get install libxml2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

However, if I try the following:
```bash
 clang test.c -I/usr/include/libxml2
```
It fixes the error with the simple C program mentioned above, so for some reason the package config doesn't seem to be considered when running the swift build.

**Comment by moosichu** [comment]
Looked into how to provide C flags to swift build, and the following worked:

```bash
swift build -Xcc -I/usr/include/libxml2
note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

note: you may be able to install libxml-2.0 using your system-packager:

    apt-get install libxml2-dev

Compile Swift Module 'Kanna' (5 sources)
Compile Swift Module 'cl_scraper' (1 sources)
Linking ./.build/debug/cl_scraper
```

**Comment by tid-kijyun** [comment]
Please remove `libxml2-dev` and reinstall.

```
$ sudo apt-get remove libxml2-dev
$ sudo apt-get install libxml2-dev
```

**Comment by moosichu** [comment]
Just to clarify, this has already been tried, the machine has been restarted, and the error has been reproduced on a completely different computer in a docker image.

**Comment by tid-kijyun** [comment]
Which Docker image do you use?
[IBM-Swift](https://github.com/IBM-Swift/swift-ubuntu-docker), [swiftdocker](https://github.com/swiftdocker/docker-swift), or other?

**Comment by Pinpickle** [comment]
Can confirm that I am getting this on a Docker image.

Set up swift/kanna environment. Then:

`Dockerfile`:

```
FROM swiftdocker/swift

RUN apt-get update && \
  apt-get install libxml2-dev

WORKDIR /swift
```

`docker-compose.yml`

```
version: '2'
services:
  swift:
    build: .
    volumes:
    - .:/swift
```

Then trying

```
docker-compose run swift
# swift build
```

I get the exact same errors as @moosichu

**Comment by tid-kijyun** [comment]
Hi @Pinpickle 

Thank you for your information.
I reproduced this issue. I'll investigate the cause.

*Note: It works properly on a `IBM-Swift/swift-ubuntu-docker`.*

**Comment by tid-kijyun** [comment]
@moosichu @Pinpickle 

The cause of this issue is that `pkg-config` is not installed in your environment.

Please run the following command:
```
$ sudo apt-get install pkg-config
```

**Comment by Pinpickle** [comment]
@tid-kijyun can confirm that this works, thanks for investigating!

Is it worth putting a note in the readme for future users of this package? It's difficult to infer what is required from the note on SwiftPM (and it is not clear at all that this is the place to go to when troubleshooting this issue).

**Comment by moosichu** [comment]
Thank you @tid-kijyun for investigating!

**Comment by tid-kijyun** [comment]
I added a note about this issue to the readme.

Thanks
